244Initials/force-app/main/default/objects/Account/fields/ARTL_Billing_Pincode__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Billing_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Pincode</label>
    <referenceTo>ARTL_Pincode__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Business_Circle_Region__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Business_Circle_Region__c</fullName>
    <label>Business Circle/ Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>CIS</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>GUJ</fullName>
            </value>
            <value>
                <fullName>India International</fullName>
            </value>
            <value>
                <fullName>KK</fullName>
            </value>
            <value>
                <fullName>KTN</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>MPCG</fullName>
            </value>
            <value>
                <fullName>MUM</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>NESA</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>RAJ</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>SAARC</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>UPE</fullName>
            </value>
            <value>
                <fullName>UPW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>WBO</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_CO_Care_Of__c.field-meta.xml
<CustomField>
    <fullName>ARTL_CO_Care_Of__c</fullName>
    <label>CO (Care Of)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Country_Code__c</fullName>
    <defaultValue>TEXT(91)</defaultValue>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Identification_Type__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Identification_Type__c</fullName>
    <label>Identification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>TAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_IsPANVerified__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IsPANVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPANVerified?</label>
    <type>Checkbox</type>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_TAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_TAN__c</fullName>
    <label>TAN</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_TL__c.field-meta.xml
<CustomField>
    <fullName>ARTL_TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TLs</relationshipName>
    <type>Lookup</type>
</CustomField>

244Initials/force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>SmartCity</fullName>
            </value>
            <value>
                <fullName>Smart City</fullName>
            </value>
            <value>
                <fullName>Telecom</fullName>
            </value>
            <value>
                <fullName>Wholesale Carrier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Lead/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Lead/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

244Initials/force-app/main/default/objects/Lead/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Global Segment</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/globalValueSets/Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>31</fullName>
    </customValue>
    <customValue>
        <fullName>32</fullName>
    </customValue>
    <customValue>
        <fullName>33</fullName>
    </customValue>
    <customValue>
        <fullName>34</fullName>
    </customValue>
    <customValue>
        <fullName>36</fullName>
    </customValue>
    <customValue>
        <fullName>39</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>41</fullName>
    </customValue>
    <customValue>
        <fullName>43</fullName>
    </customValue>
    <customValue>
        <fullName>44</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>46</fullName>
    </customValue>
    <customValue>
        <fullName>47</fullName>
    </customValue>
    <customValue>
        <fullName>48</fullName>
    </customValue>
    <customValue>
        <fullName>49</fullName>
    </customValue>
    <customValue>
        <fullName>51</fullName>
    </customValue>
    <customValue>
        <fullName>52</fullName>
    </customValue>
    <customValue>
        <fullName>53</fullName>
    </customValue>
    <customValue>
        <fullName>54</fullName>
    </customValue>
    <customValue>
        <fullName>55</fullName>
    </customValue>
    <customValue>
        <fullName>56</fullName>
    </customValue>
    <customValue>
        <fullName>57</fullName>
    </customValue>
    <customValue>
        <fullName>58</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>61</fullName>
    </customValue>
    <masterLabel>Country Code</masterLabel>
</GlobalValueSet>

244Initials/force-app/main/default/classes/ARTL_FindDuplicate.cls
global without sharing class ARTL_FindDuplicate implements vlocity_cmt.VlocityOpenInterface {
    global Boolean invokeMethod(String methodName, Map<String,Object> input, Map<String,Object> outMap, Map<String,Object> options){
        try{
            if(methodName.equals('findAccountDuplicate')){
                findAccountDuplicate(input, outMap, options);
                return true;
            }/*else if(methodName.equals('findLeadDuplicate')){
            //findLeadDuplicate(input, outMap, options);
            return true;
            }*/else if(methodName.equals('insertAccount')){
                insertAccount(input, outMap, options);
                return true;
            }else if(methodName.equals('insertLead')){
                insertLead(input, outMap, options);
                return true;
            }
        }catch(Exception ex){
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_FindDuplicate:'+methodName, '', new Map<String,Object>{'Exception'=>ex.getMessage() , 'LineNumber' => ex.getLineNumber()}, ex);
        }
        return false;
    }
    
    public static void findAccountDuplicate(Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options){
        if(input.containsKey('AccountName')){
            Account businessAccount 		= createAccountInstance(input);
            List<Account> duplicateAccount 	= new List<Account>();
            if(businessAccount != null){
                duplicateAccount 			= ARTL_CustomDuplicateRuleUtil.findDuplicateRecords(businessAccount);
                //outMap.put('AccountResult', businessAccount);
                outMap.put('DuplicateFound', (!duplicateAccount.isEmpty()) ? true : false);
            }
        }
    }
    
    public static void insertAccount(Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options){
        //Account businessAccount = input.containsKey('businessAccount') ? (Account)input.get('businessAccount') : null;
        try{
            Account businessAccount = createAccountInstance(input);
            if(businessAccount != null){
                Database.DMLOptions dml = new Database.DMLOptions();
                dml.DuplicateRuleHeader.AllowSave = true; 
                
                Database.SaveResult sr = Database.insert(businessAccount, dml); 
                if (sr.isSuccess()) { 
                    System.debug('Account inserted::'+sr.getId()); 
                    outMap.put('AccountId', sr.getId());
                }
                //insert businessAccount;
            }
        }catch(Exception ex){
            outMap.put('errorMessage',ex.getMessage());
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_FindDuplicate:insertAccount', '', new Map<String,Object>{'Exception'=>ex.getMessage() , 'LineNumber' => ex.getLineNumber()}, ex);
        }
    }
    
    public static Account createAccountInstance(Map<String, Object> input){
        Account businessAccount 	= new Account();
        Id businessAccRecordTypeId 	= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business')?.getRecordTypeId();
        String userId 				= input.containsKey('userId') ? String.valueOf(input.get('userId')): UserInfo.getUserId();
        Id tlUserId 				= [SELECT Id,ManagerId FROM User WHERE Id=:userId ]?.ManagerId;
        
        if(input.containsKey('AccountName')){
            Map<String,Object> accountDetails				= new Map<String,Object>();
            accountDetails									= (Map<String,Object>)input.get('AccountDetails');
            businessAccount.Name 							= String.valueOf(input.get('AccountName'));
            businessAccount.RecordTypeId 					= businessAccRecordTypeId;
            businessAccount.Phone							= accountDetails.containsKey('Phone') ? String.valueOf(accountDetails.get('Phone')) : null;
            businessAccount.Website							= accountDetails.containsKey('Website') ? String.valueOf(accountDetails.get('Website')) : '';
            businessAccount.ARTL_CO_Care_Of__c 				= accountDetails.containsKey('CareOf') ? String.valueOf(accountDetails.get('CareOf')) : '';
            businessAccount.ARTL_Identification_Type__c 	= accountDetails.containsKey('IdentificationType') ? String.valueOf(accountDetails.get('IdentificationType')) : '';
            businessAccount.ARTL_PAN__c						= accountDetails.containsKey('PAN') ? String.valueOf(accountDetails.get('PAN')) : '';
            businessAccount.ARTL_TAN__c						= accountDetails.containsKey('TAN') ? String.valueOf(accountDetails.get('TAN')) : '';
            businessAccount.ARTL_Category__c				= accountDetails.containsKey('Category') ? String.valueOf(accountDetails.get('Category')) : '';
            businessAccount.ARTL_Customer_Segment__c 		= accountDetails.containsKey('CustomerSegment') ? String.valueOf(accountDetails.get('CustomerSegment')) : '';
            businessAccount.ARTL_Business_Circle_Region__c 	= accountDetails.containsKey('BusinessCircleRegion') ? String.valueOf(accountDetails.get('BusinessCircleRegion')) : '';
            businessAccount.ARTL_Service_Segment__c 		= accountDetails.containsKey('ServiceSegment') ? String.valueOf(accountDetails.get('ServiceSegment')) : '';
            businessAccount.ARTL_Vertical_Segment__c 		= accountDetails.containsKey('VerticalSegment') ? String.valueOf(accountDetails.get('VerticalSegment')) : '';
            businessAccount.ARTL_Country_Code__c			= accountDetails.containsKey('CountryCode') ? String.valueOf(accountDetails.get('CountryCode')) : '';
            businessAccount.ARTL_TL__c						= String.isNotBlank(tlUserId) ? tlUserId : null;
            businessAccount.ARTL_IsPANVerified__c 			= input.containsKey('IsPanNumberVerified') ? Boolean.valueOf(input.get('IsPanNumberVerified')) : false;
            
            Map<String,Object> address 						= new Map<String,Object>();
            address 										= (Map<String,Object>)accountDetails.get('TApincode-Block');
            businessAccount.ARTL_Billing_Pincode__c 		= address.containsKey('pincodeId') ? String.valueOf(address.get('pincodeId')) : null;
            
            if(address.containsKey('pincodeId') && address.get('pincodeId') != null){
                businessAccount.BillingCity 				= address.containsKey('city') ? String.valueOf(address.get('city')) : '';
                businessAccount.BillingCountry				= address.containsKey('country') ? String.valueOf(address.get('country')) : '';
                businessAccount.BillingPostalCode			= address.containsKey('pincode') ? String.valueOf(address.get('pincode')) : '';
                businessAccount.BillingState				= address.containsKey('state') ? String.valueOf(address.get('state')) : '';
                businessAccount.BillingStreet				= address.containsKey('street') ? String.valueOf(address.get('street')) : '';
            }
        }
        return businessAccount;
    }    
    
    public static void insertLead(Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options){
        try{
            Lead businessLead = createLeadInstance(input);
        	if(businessLead != null){
            	Database.DMLOptions dml = new Database.DMLOptions();
                dml.DuplicateRuleHeader.AllowSave = true; 
                
                Database.SaveResult sr = Database.insert(businessLead, dml); 
                if (sr.isSuccess()) { 
                    System.debug('Lead inserted::'+sr.getId()); 
                    outMap.put('LeadId', sr.getId());
                }
                //insert businessAccount;
            }
        }catch(Exception ex){
            outMap.put('errorMessage',ex.getMessage());
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_FindDuplicate:insertLead', '', new Map<String,Object>{'Exception'=>ex.getMessage() , 'LineNumber' => ex.getLineNumber()}, ex);
        }
    }
    
    public static Lead createLeadInstance(Map<String, Object> input){
        Lead businessLead 	= new Lead();
        if(input.containsKey('LeadCreation') && input.get('LeadCreation') != null){
            Map<String,Object> leadDetails					= new Map<String,Object>();
            leadDetails										= (Map<String,Object>)input.get('LeadCreation');
            businessLead.Salutation							= String.valueOf(leadDetails.get('Salutation'));
            businessLead.FirstName 							= String.valueOf(leadDetails.get('FirstName'));
            businessLead.LastName 							= String.valueOf(leadDetails.get('LastName'));
            businessLead.Title 								= String.valueOf(leadDetails.get('Title'));
            businessLead.Phone  							= String.valueOf(leadDetails.get('Phone'));
            businessLead.Country_Code__c 					= String.valueOf(leadDetails.get('CountryCode'));
            businessLead.Email								= String.valueOf(leadDetails.get('Email'));
            businessLead.Related_Account__c 				= input.containsKey('AccountId') && String.valueOf(input.get('AccountId')) != null ? String.valueOf(input.get('AccountId')) : null;
            businessLead.Related_Contact__c 				= input.containsKey('ContactId') && String.isNotBlank(String.valueOf(input.get('ContactId'))) && String.valueOf(input.get('ContactId')) != 'null' ? String.valueOf(input.get('ContactId')) : null;
            businessLead.Company  							= input.containsKey('company') && String.valueOf(input.get('company')) != 'null' ? String.valueOf(input.get('company')) : '';
            businessLead.Segment__c  						= input.containsKey('Segment') && String.isNotBlank(String.valueOf(input.get('Segment'))) && String.valueOf(input.get('Segment')) != 'null'? String.valueOf(input.get('Segment')) : '';
            businessLead.NumberOfEmployees 					= input.containsKey('NoOfEmployees') && String.isNotBlank(String.valueOf(input.get('NoOfEmployees'))) && String.valueOf(input.get('NoOfEmployees')) != 'null' ? Integer.valueOf(input.get('NoOfEmployees')) : null;
            businessLead.AnnualRevenue						= input.containsKey('AnnualRevenue') && String.isNotBlank(String.valueOf(input.get('AnnualRevenue'))) && String.valueOf(input.get('AnnualRevenue')) != 'null' ? Decimal.valueOf(String.valueOf(input.get('AnnualRevenue'))) : null;
            businessLead.Website 							= leadDetails.containsKey('Website') && leadDetails.get('Website') != null ? String.valueOf(leadDetails.get('Website')) : '';
            businessLead.Campaign__c  						= String.valueOf(leadDetails.get('Campaign'));
            businessLead.ARC__c 							= Decimal.valueOf(String.valueOf(leadDetails.get('ARC')));
            businessLead.vlocity_cmt__NumberofLocations__c 	= leadDetails.containsKey('NumberofLocations') ? Integer.valueOf(leadDetails.get('NumberofLocations')) : null;
            businessLead.Description						= String.valueOf(leadDetails.get('Description'));
            businessLead.Lead_Action_Remarks__c 			= String.valueOf(leadDetails.get('LeadActionRemarks'));
            businessLead.Product_Interest__c				= leadDetails.containsKey('ProductInterest') ? String.valueOf(leadDetails.get('ProductInterest')) : null;
            businessLead.LeadSource							= input.containsKey('leadSourceFormula') && input.get('leadSourceFormula') != null ? String.valueOf(input.get('leadSourceFormula')) : '';
        }
        return businessLead;
    }  
}