244Initials/force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/objects/Contact/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Email Verification Pending</fullName>
            </value>
            <value>
                <fullName>Email Verified</fullName>
            </value>
            <value>
                <fullName>OTP Verification Pending</fullName>
            </value>
            <value>
                <fullName>OTP Verified</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

244Initials/force-app/main/default/classes/ARTL_EmailLinkVerificationController.cls
public without sharing class ARTL_EmailLinkVerificationController {
    public ARTL_EmailLinkVerificationController(){
        System.debug('DEBUGG constructor ');
    }
    
    public PageReference updateContact(){
        System.debug('DEBUGG updateContact ');
        String accId = ApexPages.currentPage().getParameters().get('id');
        String email = ApexPages.currentPage().getParameters().get('email');
        System.debug('DEBUGG accId '+ accId);
        System.debug('DEBUGG email '+ email);
        String decryptedAccountId;
        String decryptedEmail;
        If(!String.isBlank(accId)){
            decryptedAccountId = ARTL_EncryptDecryptUtil.decryptString(accId);
        }
        if(!String.isBlank(email)){
            decryptedEmail = ARTL_EncryptDecryptUtil.decryptString(email);
        }
        
        System.debug('DEBUGG account Id '+ decryptedAccountId);
        System.debug('DEBUGG email id '+ decryptedEmail);
        if(!String.isBlank(decryptedAccountId) && !String.isBlank(decryptedEmail)){
            queryContactRecord(decryptedAccountId, decryptedEmail);
        }
        return null;
    }    
    public static void queryContactRecord(String decryptedAccountId, String decryptedEmail){
        List<Contact> contactList = [SELECT Id, Email, AccountId, vlocity_cmt__Status__c 
                                     FROM Contact WHERE AccountId = :decryptedAccountId 
                                     AND Email = :decryptedEmail];
        if(!contactList.isEmpty()){
            if(contactList[0].vlocity_cmt__Status__c == ARTL_Constants.CONTACT_STATUS_EMAIL_VERIFICATION_PENDING){
                contactList[0].vlocity_cmt__Status__c = ARTL_Constants.CONTACT_STATUS_EMAIL_VERIFIED;
            }
            else if(contactList[0].vlocity_cmt__Status__c != ARTL_Constants.CONTACT_STATUS_EMAIL_VERIFICATION_PENDING){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Your verification email is invalid.'));
            }
        }
        updateContactStatus(contactList[0]);
    }
    
    public static void createVerificationUrl(Contact contactRecord){
        System.debug('DEBUGG encryptData '+ contactRecord);
        try{
            String contactRole = contactRecord.ARTL_Contact_Role__c;
            if(!String.isBlank(contactRole) && contactRole == 'Authorized Signatory'){
                String encryptedAccountId = ARTL_EncryptDecryptUtil.encryptString(contactRecord.AccountId);
                String encryptedEmailId = ARTL_EncryptDecryptUtil.encryptString(contactRecord.Email);
                System.debug('DEBUGG encryptData '+ contactRecord);
                //String encryptedTime = encryptString(contactRecord.LastModifiedDate);
                String baseUrl = System.Label.ARTL_EmailVerificationSiteUrl;//'https://business-force-5632--artldevp2.sandbox.my.salesforce-sites.com'; //Custom Label
                String finalUrl = baseUrl+'?id='+encryptedAccountId+'&email='+encryptedEmailId;
                System.debug('DEBUGG finalUrl '+ finalUrl);
                sendEmail(contactRecord, finalUrl);
            }
        }
        catch(Exception ex){
            System.debug('Exception '+ ex.getMessage() + ex.getLineNumber());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Something went wrong, please contact your system admin.'));
        }
    }
    
    public static void sendEmail(Contact contactRecord, String finalUrl){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {contactRecord.Email}; 
            mail.setToAddresses(toAddresses);
        mail.setSenderDisplayName('Salesforce Support');
        mail.setSubject('Salesforce Verification Email');
        mail.setHtmlBody('Dear '+ contactRecord.FirstName+ ' You have been registered an Authorized Signatory for '+ 
                         contactRecord.Account.Name +'. <br/> If you consent as an Authorized Signatory for '+ 
                         contactRecord.Account.Name + ', please click on the link below to complete the registration process <a href='
                         +finalUrl+'>. Click here</a>');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        Contact updateContactRecord = new Contact(Id = contactRecord.Id, 
                                                  vlocity_cmt__Status__c = ARTL_Constants.CONTACT_STATUS_EMAIL_VERIFICATION_PENDING);
        updateContactStatus(updateContactRecord);
        
    }
    
    public static void updateContactStatus(Contact contactRecord){
        update contactRecord;
    }
}